### ISSUE TITLE
Field error from list arg with nullable variable entry (nullable=optional clash?)

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-spec#1002]
Consider the following _currently valid_ schema and query:

```graphql
type Query {
  sum(numbers:[Int!]!): Int
}

query Q ($number: Int = 3) {
  sum(numbers: [1, $number, 3])
}
```

With the following variables:

```json
{
  "number": null
}
```

Now following through [6.1.2 Coercing Variable Values](https://spec.graphql.org/draft/#sec-Coercing-Variable-Values):

1. Let coercedValues be an empty unordered Map. ✅ 
2. Let variablesDefinition be the variables defined by operation. ✅ 
3. For each variableDefinition in variablesDefinition: ✅ 
   1. Let variableName be the name of variableDefinition. ✅ 
   2. Let variableType be the expected type of variableDefinition. ✅ 
   3. Assert: [IsInputType](https://spec.graphql.org/draft/#IsInputType())(variableType) must be true. ✅ 
   4. Let defaultValue be the default value for variableDefinition. ✅ 
   5. Let hasValue be true if variableValues provides a value for the name variableName. ✅ 
   6. Let value be the value provided in variableValues for the name variableName. ✅ 
   7. If hasValue is not true and defaultValue exists (including null): ✅ 
      1. Add an entry to coercedValues named variableName with the value defaultValue. ✅ 
   8. Otherwise if variableType is a Non-Nullable type, and either hasValue is not true or value is null, raise a [request error](https://spec.graphql.org/draft/#request-error). ✅ 
   9. Otherwise if hasValue is true: ✅ 
      1. If value is null: ✅ 
         1. Add an entry to coercedValues named variableName with the value null. ✅

For the variable definition `$number: Int = 3`:

- `variableType` is `Int` (NOT `Int!`).
- `defaultValue` is `3`
- `hasValue` is `true` since `number` is provided in variables (even though it's null)
- `value` is `null`

Thus `coercedValues` becomes `{ number: null }`.

When it comes to executing the field, this results in [CoerceArgumentValues()](https://spec.graphql.org/draft/#CoerceArgumentValues()) raising a field error at 5.j.iii.1 (since `[1, null , 3]` cannot be coerced to `[Int!]!`).

Had the query have been defined with `($number: Int! = 3)` then this error could not have occurred; but we explicitly allow the nullable Int with default in [IsVariableUsageAllowed()](https://spec.graphql.org/draft/#IsVariableUsageAllowed()). Presumably this is so that we can allow a default value to apply in the list, except this is a `ListValue` so there cannot be a default value there.

We've discussed "optionality" versus "nullability" a few times, but I'd like to get the WG's read on this.

Reproduction:

```js
const { graphqlSync, GraphQLSchema, GraphQLList, GraphQLNonNull, GraphQLInt, GraphQLObjectType, validateSchema } = require('graphql');

const Query = new GraphQLObjectType({
  name: 'Query',
  fields: {
    sum: {
      type: GraphQLInt,
      args: {
        numbers: {
          type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(GraphQLInt))),
        }
      },
      resolve(_, args) {
        let total = 0;
        for (const n of args.numbers) {
          total += n;
        }
        return total;
      }
    }
  }
});

const schema = new GraphQLSchema({
  query: Query
});

const errors = validateSchema(schema);
if (errors.length > 0) {
  throw errors[0];
}

{
  console.log('Testing query with variables and null');
  const result = graphqlSync({
    schema,
    source: `query Q($number: Int = 3) {sum(numbers:[1,$number,3])}`,
    variableValues: {
      number: null
    }
  });
  console.dir(result);
}
```

**Comment by mjmahone** [comment]
Yes this issue is terrible! It’s impossible to get the client to do the right thing here, unless we switched to requiring non-nullable usages to be defined by explicitly non-nullable variables. I personally am of the opinion that allowing nullable-with-default variables to be used in non-nullable positions was a mistake. 

As a note, FB’s servers are not spec compliant in this case, as we convert an explicitly null variable with a default value into the default value. So in the above request $number is coerced to 3, not null. We therefore at execution time never have an error, but we have a subtle behavioral bug: every variable with a non-null default value is in fact non-nullable! No matter how hard the client tries to send a null!

I’m fairly certain the FB-server behavior is the root cause of this weird anti-pattern, but now it would require a version bump to fix it, I think. Alternatively we could make it explicit that $number: Int = 3 is always behaviorally identicall to $number: Int! = 3.

**Comment by benjie** [comment]
Maybe we should add a note here? https://spec.graphql.org/draft/#note-65769

**Comment by benjie** [comment]
```
Testing query with variables and null
{
  errors: [
    GraphQLError: Argument "numbers" has invalid value [1, $number, 3].
        at getArgumentValues (/home/benjie/Dev/DELETEME/repro/node_modules/graphql/execution/values.js:256:13)
        at executeField (/home/benjie/Dev/DELETEME/repro/node_modules/graphql/execution/execute.js:472:48)
        at executeFields (/home/benjie/Dev/DELETEME/repro/node_modules/graphql/execution/execute.js:413:20)
        at executeOperation (/home/benjie/Dev/DELETEME/repro/node_modules/graphql/execution/execute.js:344:14)
        at execute (/home/benjie/Dev/DELETEME/repro/node_modules/graphql/execution/execute.js:136:20)
        at graphqlImpl (/home/benjie/Dev/DELETEME/repro/node_modules/graphql/graphql.js:86:31)
        at graphqlSync (/home/benjie/Dev/DELETEME/repro/node_modules/graphql/graphql.js:33:18)
        at Object.<anonymous> (/home/benjie/Dev/DELETEME/repro/script.js:35:18)
        at Module._compile (node:internal/modules/cjs/loader:1103:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
      path: [Array],
      locations: [Array],
      extensions: [Object: null prototype] {}
    }
  ],
  data: [Object: null prototype] { sum: null }
}
```

**Comment by benjie** [comment]
Related: https://github.com/graphql/graphql-spec/pull/418

**Comment by rivantsov** [comment]
Hi
guys, I am having trouble figuring out this issue, and what exactly (which part) is the trouble. Is it:
1. The spec wording/description is unclear/faulty
2. The spec wording is fine, but the algorithm in the spec is faulty and needs to be fixed
3. The spec is fine, but the implementation in graphql.js is faulty 

I am not sure, but if it is 1, then my suggestion is to add to the phrase 

> ... allowing a variable definition with a nullable type to be provided to a non-null location as long as either that variable or that location provides a default value.

we add: "... , with condition that the variable's default value's type is compatible with the use in location. "

[Here](http://spec.graphql.org/draft/#sec-All-Variable-Usages-are-Allowed.Allowing-optional-variables-when-default-values-exist)

That makes benjie's original query invalid (var default is null) and resolves it all I think, and we need to add some validation of var default values vs var usages (pre-execution). And probably change the alg in the spec.

**Comment by rivantsov** [comment]
(prev post deleted, sorry for distraction)
I do not see any way out of it, I think it remains runtime error, as it is now; it is not preventable by extra spec rules, null value is not missing value.
