### ISSUE TITLE
Is there a JSON schema to validate introspection JSON

### ISSUE THREAD

**Issue by xperiandri** [graphql/graphql-spec#786]
I use https://github.com/fsprojects/FSharp.Data.GraphQL to create GraphQL API
Sometimes it producess incorrect introspection in terms that Postman cannot generate API from it, GraphQL playground cannot read schema and `graphql-inspector` NPM package using `introspect` command displays absolutely non-descriptive error `Error: Unable to read JSON file: FILE_PATH: Syntax Error: Expected <EOF>, found Name "kind".`

So that my question is how can I determine what is wrong?
Is there a JSON schema that I can apply to my wrong JSON and figure out what is wrong?
Or can you suggest any other working approach?

**Comment by benjie** [comment]
That error _seems_ to be a syntax error rather than a content error. It sounds like there's maybe some content after the final `}`? If you could share the JSON file that generates this error we could maybe help you pinpoint it.

I don't _think_ a JSON Schema for the introspection query would help you track down a JSON syntax error, you just want a regular JSON parser for that, e.g. `JSON.parse` in your browser's console.

**Comment by dim-37** [comment]
Her it is our `introspection` 
[introspection.zip](https://github.com/graphql/graphql-spec/files/5354635/introspection.zip)
The JSON is valid.

**Comment by benjie** [comment]
I can reproduce the issue with this script:

```js
const fs = require("fs");
const { buildClientSchema, printSchema } = require("graphql");

const json = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
if (json.errors) {
  throw new Error(
    `Errors in introspection: ${JSON.stringify(json.errors, null, 2)}`
  );
}
const schema = buildClientSchema(json.data);
console.log(printSchema(schema));
```

results in:

```
/home/benjie/Dev/graphile/graphile-engine/node_modules/graphql/language/parser.js:1404
    throw (0, _syntaxError.syntaxError)(this._lexer.source, token.start, "Expected ".concat(kind, ", found ").concat(getTokenDesc(token)));
    ^
GraphQLError: Syntax Error: Expected <EOF>, found Name "kind"
    at syntaxError (/home/benjie/Dev/graphile/graphile-engine/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (/home/benjie/Dev/graphile/graphile-engine/node_modules/graphql/language/parser.js:1404:40)
    at parseValue (/home/benjie/Dev/graphile/graphile-engine/node_modules/graphql/language/parser.js:54:10)
    at buildInputValue (/home/benjie/Dev/graphile/graphile-engine/node_modules/graphql/utilities/buildClientSchema.js:291:118)
    at /home/benjie/Dev/graphile/graphile-engine/node_modules/graphql/jsutils/keyValMap.js:27:24
    at Array.reduce (<anonymous>)
    at keyValMap (/home/benjie/Dev/graphile/graphile-engine/node_modules/graphql/jsutils/keyValMap.js:26:15)
    at buildInputValueDefMap (/home/benjie/Dev/graphile/graphile-engine/node_modules/graphql/utilities/buildClientSchema.js:284:35)
    at fields (/home/benjie/Dev/graphile/graphile-engine/node_modules/graphql/utilities/buildClientSchema.js:257:16)
    at resolveThunk (/home/benjie/Dev/graphile/graphile-engine/node_modules/graphql/type/definition.js:438:40) {
  locations: [ { line: 1, column: 3 } ]
}
```

By running this with the debugger on:

```
node --inspect-brk introspection-json-to-schema.js ~/Downloads/graphql-spec-786-introspection.json
```

it reveals the error relates to `A kind of registri culture` / EnumValue:

![Screenshot_20201009_144736](https://user-images.githubusercontent.com/129910/95590799-6beee300-0a3e-11eb-94d5-dbb1ab31e64b.png)

By walking up a couple frames it seems it relates to the `InputCulture` input object's `kind` field:

```json
            {
              "name": "kind",
              "description": null,
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "defaultValue": "A kind of registri culture"
            },

```

The GraphQL spec, [4.5.4 states](https://spec.graphql.org/June2018/#sec-The-__InputValue-Type):

> defaultValue may return a String encoding (using the GraphQL language) of the default value used by this input value in the condition a value is not provided at runtime. If this input value has no default value, returns null.


Here the defaultValue given is **NOT** encoded, so the string `A kind of registri culture` is being parsed as GraphQL, the `A` is being interpretted as an enum value, and nothing is expected after that (hence it expecting an EOF), resulting in this causing the failure.

It sounds like `__InputValue.defaultValue` is incorrectly implemented in the FSharp GraphQL implementation.

**Comment by benjie** [comment]
(The correct value would be something like:

```json
              "defaultValue": "\"A kind of registri culture\""
```
)

**Comment by xperiandri** [comment]
Ah, yes, it is a mistake in our code

**Comment by benjie** [comment]
Glad to help; I think you can close this issue now?

**Comment by xperiandri** [comment]
Basically yes.
But I wonder why must it be escaped?

**Comment by xperiandri** [comment]
@jberzy

**Comment by benjie** [comment]
I'm going to go ahead and close this...

**Comment by pavelkornev** [comment]
@benjie, anyway, is there a JSON Schema I can use to validate introspection format? E.g. i want to detect issues like the property `fields` is missing in the type definition.

**Comment by benjie** [comment]
I don't know of one; I'm not even sure how you'd go about writing one given how flexible GraphQL introspection queries are.
